image: python:3.11

before_script:
  - "pip install -U platformio"

build:
  script:
    - "pio run --environment uno_r4_minima_release"
  artifacts:
    paths:
      - .pio/build/uno_r4_minima_release/*.zip